### ISSUE TITLE
`#[docify::export_content]`

### ISSUE THREAD

**Issue by kianenigma** [sam0x17/docify#11]
is only applicable to `fn` items, acts exactly like `#[docify::export]`, but it will only export the body of the function.

**Comment by sam0x17** [comment]
I would extend this to be called `#[docify::export_contents]` and apply to any item that has some notion of contents... body in the case of `ItemFn`, `contents` in the case of `ItemMod`, and others... shouldn't be hard to add

**Comment by sam0x17** [comment]
making a note that we will want to automatically un-indent these (already something we can do with our functions), as per #13
