### ISSUE TITLE
format the final outcome

### ISSUE THREAD

**Issue by kianenigma** [sam0x17/docify#13]
As I explored in #12, it is possible to format the final outcome one more time. If we implement things like #11, I think this will be much better. 

Imagine 

```rust
#[docify::export_content]
fn body() {
    let a = 10;
}
```

will export to 

```rust
    let a = 10;
```

As things stand now. I argue that almost always, you don't want the indentation. 

I would either make the indentation optional and specified by the `embed!`, or make it be the default for the sake of simplicity.

**Comment by sam0x17** [comment]
in my implementation of `#[docify::export_conrtent]` I would un-indent automatically, we already functions for this in docify so I'll use them there
